addons:
  apt:
    packages:
      - make
      - gcc
      - libunwind8
      - libssl-dev
      - unzip
      - gettext
      - libcurl4-openssl-dev
      - libicu-dev
      - zlib1g
sudo: false
script:
- ". ./build.sh"