language: csharp
mono: none
dist: xenial
sudo: required
dotnet: 3.0
addons:
  apt:
    packages:
      - make
      - gcc
script:
- ". ./build.sh"
global:
  - DOTNET_SKIP_FIRST_TIME_EXPERIENCE=true
  - DOTNET_CLI_TELEMETRY_OPTOUT=1
