version: LDB-{branch}-{build}

test: off

install:
  - cmd: @powershell -NoProfile -ExecutionPolicy unrestricted -Command "&{$Branch='dev';$wc=New-Object System.Net.WebClient;$wc.Proxy=[System.Net.WebRequest]::DefaultWebProxy;$wc.Proxy.Credentials=[System.Net.CredentialCache]::DefaultNetworkCredentials;Invoke-Expression ($wc.DownloadString('https://raw.githubusercontent.com/dotnet/cli/master/scripts/obtain/install.ps1'))}"
  - ps: $env:DOTNET_BUILD_VERSION = $env:APPVEYOR_BUILD_NUMBER

build_script:
  - cmd: build.cmd
  
artifacts:
  - path: artifacts\Release\*.nupkg

deploy:
  - provider: NuGet
    server: https://www.myget.org/F/lightning-net
    api_key:
      secure: up5/TlcwTcVz+7wVHGnQ1q9iJOdkk4UNehGWaxQ8TqQ21iNqJr8j8m36bTBXMAaO
    skip_symbols: true
    artifact: /.*\.nupkg/