version: LDB-{branch}-{build}

test: off

install:
  - ps: mkdir -Force ".\build\" | Out-Null
  - ps: Invoke-WebRequest "https://raw.githubusercontent.com/dotnet/cli/rel/1.0.0/scripts/obtain/install.ps1" -OutFile ".\build\installcli.ps1"
  - ps: $env:DOTNET_INSTALL_DIR = "$pwd\.dotnetcli"
  - ps: $cliversion = (Get-Content -Path $globalJson -Raw | ConvertFrom-JSON).sdk.version
  - ps: '& .\build\installcli.ps1 -Channel "preview" -version "$env:cliversion" -InstallDir "$env:DOTNET_INSTALL_DIR" -NoPath'
  - ps: $env:Path = "$env:DOTNET_INSTALL_DIR;$env:Path"
  - ps: $env:DOTNET_BUILD_VERSION = $env:APPVEYOR_BUILD_NUMBER

build_script:
  - cmd: build.cmd
  
artifacts:
  - path: artifacts\Release\*.nupkg

deploy:
  - provider: NuGet
    server: https://www.myget.org/F/lightning-net
    api_key:
      secure: up5/TlcwTcVz+7wVHGnQ1q9iJOdkk4UNehGWaxQ8TqQ21iNqJr8j8m36bTBXMAaO
    skip_symbols: true
    artifact: /.*\.nupkg/